--[[
    init.lua
    Created: 02/09/2024 19:04:55
    Description: Autogenerated script file for the map hub_small.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local hub_small = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---hub_small.Init(map)
--Engine callback function
function hub_small.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---hub_small.Enter(map)
--Engine callback function
function hub_small.Enter(map)

  GAME:FadeIn(20)

end

---hub_small.Exit(map)
--Engine callback function
function hub_small.Exit(map)


end

---hub_small.Update(map)
--Engine callback function
function hub_small.Update(map)


end

---hub_small.GameSave(map)
--Engine callback function
function hub_small.GameSave(map)


end

---hub_small.GameLoad(map)
--Engine callback function
function hub_small.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return hub_small

