--[[
    init.lua
    Created: 02/09/2024 19:04:55
    Description: Autogenerated script file for the map hub_small.
]]--
-- Commonly included lua functions and data
require 'common'
require 'HubManager'

-- Package name
local hub_small = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---hub_small.Init(map)
--Engine callback function
function hub_small.Init(_)

    --This will fill the localized strings table automatically based on the locale the game is
    -- currently in. You can use the MapStrings table after this line!
    MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---hub_small.Enter(map)
--Engine callback function
function hub_small.Enter(_)
    if not SV.Intro.HubReached then
        SV.Intro.HubReached = true
        _HUB.initializePlotData()
    end
    _HUB.LoadBuildings()
    _HUB.ShowTitle()
end

---hub_small.Exit(map)
--Engine callback function
function hub_small.Exit(map)

end

---hub_small.Update(map)
--Engine callback function
function hub_small.Update(_)

end

---hub_small.GameSave(map)
--Engine callback function
function hub_small.GameSave(_)

end

---hub_small.GameLoad(map)
--Engine callback function
function hub_small.GameLoad(_)
    _HUB.ShowTitle()
end

-------------------------------
-- Entities Callbacks
-------------------------------

function hub_small.Entrance_home_Touch(obj, activator)
    PrintInfo("Triggered Entrance_home_Touch")
    --TODO connect maps
end

function hub_small.Storage_home_Action(obj, activator)
    COMMON.ShowTeamStorageMenu()
end

function hub_small.Entrance_office_Touch(obj, activator)
    PrintInfo("Triggered Entrance_office_Touch")
    --TODO connect maps
end

function hub_small.Assembly_office_Action(obj, activator)
    COMMON.ShowTeamAssemblyMenu(obj, function() end)
end

function hub_small.NPC_1_Action(obj, activator)
    PrintInfo("Triggered NPC_1_Action")
end

function hub_small.NPC_2_Action(obj, activator)
    PrintInfo("Triggered NPC_2_Action")
end

function hub_small.NPC_3_Action(obj, activator)
    PrintInfo("Triggered NPC_3_Action")
end

return hub_small

