--[[
    init.lua
    Created: 11/01/2023 17:31:57
    Description: Autogenerated script file for the map intro_house.
]]--
-- Commonly included lua functions and data
require 'common'
require 'CommonFunctions'
require 'zone.intro.character_menu'

-- Package name
local intro_house = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---intro_house.Init(map)
--Engine callback function
function intro_house.Init(map)

    --This will fill the localized strings table automatically based on the locale the game is
    -- currently in. You can use the MapStrings table after this line!
    MapStrings = COMMON.AutoLoadLocalizedStrings()
end

---intro_house.Enter(map)
--Engine callback function
function intro_house.Enter(map)
    intro_house.PlotScripting()
end

---intro_house.Exit(map)
--Engine callback function
function intro_house.Exit(map)


end

---intro_house.Update(map)
--Engine callback function
function intro_house.Update(map)


end

---intro_house.GameSave(map)
--Engine callback function
function intro_house.GameSave(map)


end

---intro_house.GameLoad(map)
--Engine callback function
function intro_house.GameLoad(map)
    intro_house.PlotScripting()
end

-------------------------------
-- Entities Callbacks
-------------------------------
function intro_house.PlotScripting()
    if not SV.intro_completed then
        intro_house.CharacterSelect()
    else
        GROUND:EnterGroundMap('Map???', 'Entrance????') --TODO fail safe. If player somehow gets to the personality test after seeing the first intro cutscene, warp them to ???.
    end
end

function intro_house.CharacterSelect()

    GAME:CutsceneMode(true)
    UI:ResetSpeaker()
    SOUND:FadeOutBGM()

    --move partner and hero away and move camera to starting position.
    GAME:MoveCamera(192, 156, 1, false)

    --initialize some save data
    _DATA.Save.ActiveTeam:SetRank("normal")
    _DATA.Save.ActiveTeam.Money = 0
    _DATA.Save.ActiveTeam.Bank = 0
    _DATA.Save.NoSwitching = true--switching is not allowed

    --remove any team members that may exist by default for some reason
    local party_count = _DATA.Save.ActiveTeam.Players.Count
    for ii = 1, party_count, 1 do
        print("deleting party"..tostring(ii))
        _DATA.Save.ActiveTeam.Players:RemoveAt(0)
    end

    local assembly_count = GAME:GetPlayerAssemblyCount()
    for i = 1, assembly_count, 1 do
        print("deleting assembly"..tostring(i))
        _DATA.Save.ActiveTeam.Assembly.RemoveAt(i-1)--not sure if this permanently deletes or not...
    end

    local map = _ZONE.CurrentGround
    local pelipper = CH('Intro_Pelipper')
    COMMON_FUNC.initDialogue(pelipper, "What a day...", "Sigh")
    GAME:FadeIn(20)

    GROUND:MoveToMarker(pelipper, map:GetMarker("Center"), false, 2)
    GROUND:CharAnimateTurn(pelipper, Direction.Right, 4, true)
    COMMON_FUNC.initDialogue(pelipper, "Nothing ever happens in that damned office,[pause=10] yet you always feel like you have to rush everything.", "Sad")
    UI:WaitShowDialogue("I need a break.[pause=0] No,[pause=10] i need something stimulating.[pause=0] I'm not saying i want to go on an adventure,[pause=10] but...")
    GROUND:CharAnimateTurn(pelipper, Direction.Left, 4, true)
    UI:WaitShowDialogue("Oh,[pause=10] who am i kidding?[pause=0] Of course i'd love to...")
    GROUND:CharSetEmote(pelipper, "question", 1)
    SOUND:PlayBattleSE('EVT_Emote_Confused')
    COMMON_FUNC.initDialogue(pelipper, "Hm?", "Worried")

    GROUND:MoveToMarker(pelipper, map:GetMarker("Paper"), false, 2)
    UI:WaitShowDialogue("What's this, now?")
    GAME:WaitFrames(60)
    GROUND:CharSetEmote(pelipper, "exclaim", 1)
    SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("It's from the Federation?")

    UI:WaitShowDialogue("\"Congratulations![pause=0] You have been selected as an Exploration Team Federation representative for our newest exploration initiative.\"")
    UI:WaitShowDialogue("\"You will be paired up with an agent of our choosing to explore and,[pause=10] if necessary,[pause=10] colonize a newly discovered region.\"")
    UI:WaitShowDialogue("\"Your task will involve accompanying them to the identified camp site and periodically reporting the mission state to the Federation.\"")
    UI:WaitShowDialogue("\"Attached to this letter you will find your new team member's id file.[pause=0] We expect you to confirm or deny your participation within 2 business by filling the attached confirmation letter and handing it to your office head.\"")
    UI:WaitShowDialogue("\"Signed:[pause=30] ETF\"")

    -- beat wings like chatot, idk
    COMMON_FUNC.initDialogue(pelipper, "Wait what?[pause=0] They want[pause=5] ME for a mission?", "Surprised")
    COMMON_FUNC.initDialogue(pelipper, "Were they spying me or something?", "Worried")
    COMMON_FUNC.initDialogue(pelipper, "Well,[pause=10] regardless,[pause=10] who am i to say no?[pause=0] I'd love to join this expedition,[pause=10] or whatever it is!", "Happy")

    COMMON_FUNC.initDialogue(pelipper, "Now,[pause=10] let's see who this team member is...", "Normal")

    -- display paper bg and open character creation menu

    UI:WaitShowDialogue("Alright![pause=0] this [player name] fellow seems interesting![pause=0] Can't wait to meet [player pronouns]!")
    UI:WaitShowDialogue("I should probably fill this confirmation letter in, as well,[pause=10] and then go to bed.")
    COMMON_FUNC.initDialogue(pelipper, "Wow, i can't wait...", "Happy")

    -- make the pokémon do some animation to display excitedness
    GAME:FadeOut(20)
    -- wait 30 or 60 frames idk
    -- show "The next week..." text in the center
    -- tp to the mission start area
end

return intro_house

