--[[
    init.lua
    Created: 02/21/2024 02:13:24
    Description: Autogenerated script file for the map office_tier1.
]]--
-- Commonly included lua functions and data
require 'common'
require 'HubManager'

-- Package name
local office_tier1 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---office_tier1.Init(map)
--Engine callback function
function office_tier1.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---office_tier1.Enter(map)
--Engine callback function
function office_tier1.Enter(map)
  GAME:FadeIn(20)
end

---office_tier1.Exit(map)
--Engine callback function
function office_tier1.Exit(map)

end

---office_tier1.Update(map)
--Engine callback function
function office_tier1.Update(map)

end

---office_tier1.GameSave(map)
--Engine callback function
function office_tier1.GameSave(map)

end

---office_tier1.GameLoad(map)
--Engine callback function
function office_tier1.GameLoad(map)
  _HUB.ShowTitle()
end

-------------------------------
-- Entities Callbacks
-------------------------------
function office_tier1.Pelipper_Talk_Action(obj, activator)
  PrintInfo("Triggered Pelipper_Talk_Action")
end

function office_tier1.Exit_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  local pos = _HUB.getPlotOriginList()[2]
  local marker = _HUB.ShopBase["office"].Graphics[1].Marker_Loc
  GAME:EnterGroundMap(_HUB.getHubMap(), "Entrance")
  _HUB.SetMarker(pos.X + marker.X, pos.Y + marker.Y)
end

return office_tier1

