--[[
    init.lua
    Created: 02/15/2024 17:42:20
    Description: Autogenerated script file for the map hub_zone.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local hub_zone = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---hub_zone.Init(zone)
--Engine callback function
function hub_zone.Init(zone)

end

---hub_zone.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function hub_zone.EnterSegment(zone, rescuing, segmentID, mapID)

end

---hub_zone.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function hub_zone.ExitSegment(zone, result, rescue, segmentID, mapID)

end

---hub_zone.Rescued(zone, name, mail)
--Engine callback function
function hub_zone.Rescued(zone, name, mail)

end

return hub_zone

