--[[
    init.lua
    Created: 12/13/2024 12:25:03
    Description: Autogenerated script file for the map ancient_trail.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local ancient_trail = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---ancient_trail.Init(zone)
--Engine callback function
function ancient_trail.Init(zone)


end

---ancient_trail.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function ancient_trail.EnterSegment(zone, rescuing, segmentID, mapID)


end

---ancient_trail.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function ancient_trail.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---ancient_trail.Rescued(zone, name, mail)
--Engine callback function
function ancient_trail.Rescued(zone, name, mail)


end

return ancient_trail

